### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by ghost** [timothyasp/nova-badge-field#1]
![image](https://user-images.githubusercontent.com/737550/44564615-8a18fc80-a76c-11e8-946b-480fcf020f74.png)

**Comment by cfreak** [comment]
Same Problem here :-( Can you help?

**Comment by jorgv** [comment]
Try to run
`npm run production`

If doesn't work run it on /vendor/timothyasp/nova-badge-field

**Comment by timothyasp** [comment]
Sorry about that - just pushed up the `dist` directory.  Looks like `nova:field` command adds a gitignore for the `dist/` dir by default, which isn't great for distribution.  Unclear if this is best practice, but for now that should resolve the problem.
