### ISSUE TITLE
Set color and background for all values except defined

### ISSUE THREAD

**Issue by Yakubina** [timothyasp/nova-badge-field#11]
Hi!
I'm looking for a next thing. 
I set color and background for 2 values, that I know they could be there. 
And third value is a datetime, which could have any value, so I cant predict its value and add it to options array. 
How to define common color for all these values that were not defined as known options?

**Comment by timothyasp** [comment]
This isn't possible right now.  This was built as a display option for nova `Select` fields on resource index and detail pages, which don't handle `n`-number of value options.   

One option would be to  I think the best way to handle this would be to fork this project and add a `->default()` option.

Something like 
```
->default([
   'background' => '#ff000'
   'color' => '#ffffff'
])
```
