### ISSUE TITLE
This Badge field doesn't seem to work in Nova 3.0 

### ISSUE THREAD

**Issue by Razorsheep** [timothyasp/nova-badge-field#15]
I've tried implementing this in a project in L7 + Nova 3.0 and it doesn't render any badges no matter how I set it up. 

Is it possible it needs an update for nova 3.0?

**Comment by timothyasp** [comment]
I'll happily accept a pull updating things - I haven't checked out L7 + Nova 3.0 yet.

**Comment by cord** [comment]
works here with L7 + Nova 3

**Comment by mnsuccess** [comment]
This doesn't work with Laravel 8 + Nova  3

**Comment by timothyasp** [comment]
Just pushed update that works with L9 + Nova 4.

**Comment by timothyasp** [comment]
If anyone is still running v3 and wants to contribute a fix, I'll happily merge.  But I was seeing things working with L9 + Nova 3 with v1.0.4 of this package, so I'm going to close this.
