### ISSUE TITLE
Outline style

### ISSUE THREAD

**Issue by cord** [timothyasp/nova-badge-field#16]
Would be great if you could add the option to define the border / border-color:

```
   ->colors([
      'option1' => [
          'background' => '#ffffff',
          'color' => '#ffa500',
          'border-color' => '#ffa500' // default: 1px solid
          'border' => '1px solid #ffa500', // full controll
      ],
```

or full style control:
```
   ->colors([
      'option1' => [
          'style' => 'color: #ffa500; border: 1px solid #ffa500'
      ],
```

or outline option, which uses color and background:
```
->outline()
```

e.g. to get an outline style like this

![alert-incidents 2020-06-23 11-40-32](https://user-images.githubusercontent.com/158588/85388753-c410e080-b546-11ea-83fe-a5de6ef1d3b4.png)

![alert-incidents 2020-06-23 11-40-47](https://user-images.githubusercontent.com/158588/85388757-c5420d80-b546-11ea-9707-ff0d01fddb5d.png)

**Comment by timothyasp** [comment]
Hey @cord - this sounds totally reasonable.

Kind of inline with what's coming in [laravel/nova#905](https://github.com/laravel/nova/pull/905) - I'd merge in a pull that adds an `extraClasses()` method to handle these style changes.  Much more extensible and inline with what we're seeing in the rest of Nova.

Does that work?

**Comment by timothyasp** [comment]
Added an `extraClasses()` method with the latest release.
