### ISSUE TITLE
Badges not Stackable in Nova 3.7+

### ISSUE THREAD

**Issue by babul** [timothyasp/nova-badge-field#17]
Thanks so much for this package!

Noticed that it does not work as expected when combined with Nova's new Stack field (https://nova.laravel.com/docs/3.0/resources/fields.html#stack-field). 

Instead of stacked, badges are shown side-by-side like as follows.

<img width="163" alt="image" src="https://user-images.githubusercontent.com/391316/89574816-5b2db100-d7f2-11ea-8977-0c12a1905701.png">

We are building a custom "ticket" system into an application, and stacked fields allow a greater visual density of information horizontally.

**Comment by timothyasp** [comment]
This is a good idea - I haven't had a chance to check out the stack field. I'll happily merge a pull that adds this functionality.

**Comment by timothyasp** [comment]
Just added some customization tools to let you do this if it's still a thing, and you're on Nova v4

```
Badge::make('Field')
->extraClasses('flex mb-2')
```

on the first badge field in the stack would give you what you're looking for!

**Comment by babul** [comment]
> Just added some customization tools to let you do this if it's still a thing, and you're on Nova v4
> 
> ```
> Badge::make('Field')
> ->extraClasses('flex mb-2')
> ```
> 
> on the first badge field in the stack would give you what you're looking for!

Thanks so much!
