### ISSUE TITLE
Badges Don't Respect Nova's Text Alignment Methods

### ISSUE THREAD

**Issue by nickpoulos** [timothyasp/nova-badge-field#18]
For smaller badges that may not take up the entire column space, I tried adding Nova's built in methods: 

 `->textAlign('center')` and `->withMeta(['textAlign' => 'center'])`
 
However because the badges are using spans, they do not center inside the column correctly. 

I imagine there is some custom css needed when text alignment changes are detected

**Comment by timothyasp** [comment]
This should be fixed in the latest update.  v2.0.1

If not, you can add tailwind classes with the `->extraClasses()` method to align things however you need.
