### ISSUE TITLE
Allow using displayUsingLabels

### ISSUE THREAD

**Issue by agustinprod** [timothyasp/nova-badge-field#3]
I'm using this component to display a boolean field with green or red, but want to show a custom label (Active / Disabled). This component extends from select, should be easy to use displayUsingLabels feature. Thanks!

**Comment by timothyasp** [comment]
Hey @killgt - It sounds like the [Boolean Field](https://nova.laravel.com/docs/1.0/resources/fields.html#boolean-field) might be a better fit for the use case you're describing.  

If you want to submit a pull with the changes your requesting, I'm more than happy to review and merge.
