### ISSUE TITLE
Change color of Text

### ISSUE THREAD

**Issue by ServerJunge** [timothyasp/nova-badge-field#5]
Hi,

is it possible to make the text of the badge alway white?

**Comment by timothyasp** [comment]
Yea, I can look into doing that.  Not sure if it'd be useful to be very explicit about things and do something like...

```
Badge::make()
->colors([
   "Field" => [
      "background" => '#333333',
      "text" => '#fff'
   ]
])
```

where the existing option defaults to field to background map (like below) where I pick white or black for contrasting colors.
```
->colors([
     'Field' => '#color'
])
```

or if it'd be better to make it a global setting, like 

```
Badge::make()
->colors([])
->textColor('#fff')
```


Thoughts?

**Comment by horaceho** [comment]
How about defining the ````colors```` in an array? i.e.:

                ->colors([
                    'Pending' => ['#D30000', '#000000'],
                    'Done' => ['#FC6600'],
                ]),

1st element is background color, 2nd element is text color. If 2nd element is missing, text color follows default.

**Comment by ServerJunge** [comment]
I like the idea of being explicit.

**Comment by Livijn** [comment]
I would prefer being explicit and keeping the array keys to CSS properties.

```
Badge::make()
->colors([
   "field_name" => [
      "background" => '#333333',
      "color" => '#fff', // instead of text
   ]
])
```

**Comment by timothyasp** [comment]
Great - explicit, nested keys for background and text color defs.  i'll get working on this and get it merged in.

**Comment by timothyasp** [comment]
1.0.2 contains this feature.
