### ISSUE TITLE
don't show in index

### ISSUE THREAD

**Issue by Mrspolly87** [timothyasp/nova-badge-field#6]
hi, i have this code 

![image](https://user-images.githubusercontent.com/40707006/45187485-68048d00-b1f6-11e8-87ae-0fc90f501b11.png)

in edit and the view i can see my select  
![image](https://user-images.githubusercontent.com/40707006/45187402-2d9af000-b1f6-11e8-8dd1-5fee08dbbc89.png)

but in index no
![image](https://user-images.githubusercontent.com/40707006/45187457-4c00eb80-b1f6-11e8-94ed-66772d0cb67e.png)

**Comment by timothyasp** [comment]
You need to set `->colors([
   'EMPRESA' => '#color'
])` 

for example.
