### ISSUE TITLE
what is the name to use?

### ISSUE THREAD

**Issue by lvltech-mx** [timothyasp/nova-badge-field#7]
in the docs dont specify the name to use on de nova resource.

**Comment by Dontorpedo** [comment]
same, 

"Class colors not found" when i try to use this package

**Comment by gbrits** [comment]
use Timothyasp\Badge\Badge;

    Badge::make('Status','incident_status')
                 ->options(['Open','Closed'])
                 ->colors([
                    'Open' => '#00ff00',
                    'Closed' => '#ff0000'
                 ]),

**Comment by timothyasp** [comment]
Updated the README with `use Timothyasp\Badge\Badge;`
